"""last_seen in user model

Revision ID: 291e5c378ac0
Revises: f872d4a5383e
Create Date: 2021-03-31 09:09:50.009525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '291e5c378ac0'
down_revision = 'f872d4a5383e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    # ### end Alembic commands ###
