"""empty message

Revision ID: 2eb32f2b063b
Revises: 3e7bc06a8f35
Create Date: 2021-04-19 09:11:04.798968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eb32f2b063b'
down_revision = '3e7bc06a8f35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_author', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_author')
    # ### end Alembic commands ###
