"""added user flags

Revision ID: a1a5bb293eff
Revises: 1fb9f90fca80
Create Date: 2021-04-03 16:06:34.258485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a5bb293eff'
down_revision = '1fb9f90fca80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('vip', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'vip')
    op.drop_column('user', 'admin')
    # ### end Alembic commands ###
