"""empty message

Revision ID: a5581bafac62
Revises: 557907087493
Create Date: 2021-04-21 16:48:26.408249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5581bafac62'
down_revision = '557907087493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('html', sa.String(length=64000), nullable=True))
    op.add_column('article', sa.Column('internal_name', sa.String(length=64), nullable=True))
    op.add_column('article', sa.Column('source', sa.String(length=32000), nullable=True))
    op.create_index(op.f('ix_article_internal_name'), 'article', ['internal_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_internal_name'), table_name='article')
    op.drop_column('article', 'source')
    op.drop_column('article', 'internal_name')
    op.drop_column('article', 'html')
    # ### end Alembic commands ###
