"""empty message

Revision ID: f15a03081b4a
Revises: a5581bafac62
Create Date: 2021-04-28 18:32:44.444314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f15a03081b4a'
down_revision = 'a5581bafac62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('sub_title', sa.String(length=64), nullable=True))
    op.add_column('article', sa.Column('title', sa.String(length=64), nullable=True))
    op.drop_column('article', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('article', 'title')
    op.drop_column('article', 'sub_title')
    # ### end Alembic commands ###
